<?php

return [
    'rsa' => [
        'publicKey'  => "-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GdRoWqyHNwvwL8tmtYtD95m5HZD5/DLdnouTPXmOIlpZG
ufPx9zW/9qTeUQ5yuwIDAQAB
-----END PUBLIC KEY-----",


        'privateKey' => "-----BEGIN RSA PRIVATE KEY-----
MIICXgIBAAKBgQDe6ReTXj8SEXiT7PScTEeujPv55eiF5cXnK2avBc+ZJTgbbq2I
q6LhWMxThGwMCNg/05CoDBT3JR+WPmU1yueG/v3SLJHk6t2fw1RkKShh2PU3dRoW
qyHNwvwL8tmtYtD95m5HZD5/DWOn1UsSnBAQJBAIzWyfECT+5Z2R6IUT9/VqGcMICa
RLQtBsq8QiafSE8o0pUVf5kxc3Tcf6wBOXK+SdbsAE6u2IGYPigf1Mzlgz0CQQDN
OrCPZaVXtVbzyLoWcI5b/0mxtzWDp8R+QCD91RlEe8JGQgYElIKnNDdYFzGHHr/k
hQGwJKXseU3TgrupQvoBAkEA7pyPyRKk9XDuj+fADbHENQVOxAlgMf8GajNCNcZ4
uc+tWj6K8UslC/mRI/EVpRFEitYYlTildDioAqKQAz7VrA==
-----END RSA PRIVATE KEY-----",
    ],
];
